  
version: 0.1
phases:
  install:
    commands:
      - mkdir hello
      - echo hello | xargs -n 1 cp -R util lib
      - echo Trying to package...
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket serverlessbucket10 
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
